### ISSUE TITLE
Login Hangup

### ISSUE THREAD

**Issue by McBrettorrson** [cfms-website/cfms-website.github.io#153] opened 2018-08-31 02:47 UTC
When using microsoft edge, the login window never pops up. While using google chrome the window loads but hangs indefinitely in the loading stage after submitting credentials.

**Comment by adelarezki** [comment] 2018-08-31 08:01
The issue is currently being investigated by the IT staff.

**Comment by pyarmak** [comment] 2018-08-31 14:51
Fixed in 4177ce0f5fdfca6186ee1bf65a869f55aa6b1f39.

**Closed by pyarmak** 2018-08-31 14:51 UTC
Labels: bug
